# -*- coding: utf-8 -*-
"""Meitei_lon to English

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qJGlhqPUNQs50cVogvb5FTtEodlNi9HT
"""

import gradio as gr
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

# Load model & tokenizer
model_name = "DayanandaThokchom/N7-T5-small-EN-MNI"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

# Translation function
def translate_text(text):
    if not text.strip():
        return "Please enter some text."

    prompt = f"translate English to meitei mayek:{text}"
    inputs = tokenizer(prompt, return_tensors="pt").input_ids

    outputs = model.generate(
        inputs,
        max_new_tokens=50,
        do_sample=True,
        top_k=10,
        top_p=0.50
    )

    decoded_output = tokenizer.decode(outputs[0], skip_special_tokens=True)
    cleaned_output = decoded_output.split('.')[0] if '.' in decoded_output else decoded_output
    return cleaned_output

# Gradio UI
demo = gr.Interface(
    fn=translate_text,
    inputs=gr.Textbox(label="Enter English text", placeholder="Type here..."),
    outputs=gr.Textbox(label="Meitei Mayek Translation"),
    title="English → Meitei Mayek Translator",
    description="Translate English sentences into Meitei Mayek using the N7-T5-small model."
)

if __name__ == "__main__":
    demo.launch()

